FROM node:10.13-alpine

WORKDIR /home/node/app

# Install deps
COPY ./Views/package* ./
RUN npm install && \
    npm cache clean --force

COPY ./Views/build ./build
COPY ./Views/oc-pizzas/dist/oc-pizzas/ ./dist

# Expose ports (for orchestrators and dynamic reverse proxies)
EXPOSE 3000

# Start the app
CMD npm start